version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: daily
    groups:
      all-dependencies:
        patterns:
          - "*"

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    groups:
      vendor-libs:
        patterns:
          - "*"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    groups:
      all-actions:
        patterns:
          - "*"
